### PR TITLE
Implement tracing for Doobie 

### PR DESCRIPTION
**Pull request by calvinlfer**
also include an example Doobie application which connects to Postgres

special thanks to @soujiro32167 for his help with this

### CODE REVIEW

**Comment by calvinlfer** [comment]
TODO:
* Test(s)
* Documentation

**Comment by calvinlfer** [comment]
image

**Comment by calvinlfer** [comment]
Closes https://github.com/kaizen-solutions/trace4cats-zio-extras/issues/15

**Review by soujiro32167 — APPROVED** [review]
🤘

**Pull request merged**
